apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  description: ${{ values.description | dump }}
  annotations:
    gitlab.com/project-slug: 'AgileDMBSandbox/${{orgname}}/mesh.repository/${{ values.domain | replace(r/domain:| |-/, "") }}/${{ values.dataproduct.split(".")[1] | replace(r/ |-/g, "") }}/${{ values.name.split(" ") | join("") | lower }}'
    backstage.io/techdocs-ref: dir:.
  tags:
    - snowflake
    - storage
spec:
  type: storage
  lifecycle: experimental
  owner: ${{ values.developmentGroup | dump }}
  system: ${{ values.dataproduct | dump }}
  domain: ${{ values.domain | dump }}
  mesh:
    name: ${{ values.name | dump }}
    fullyQualifiedName: ${{ values.fullyQualifiedName | dump }}
    description: ${{ values.description | dump }}
    kind: storage
    version: ${{ values.identifier.split(".")[2] + ".0.0" }}
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    platform: Snowflake
    technology: Snowflake
    StorageType: Database
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    specific:
      database: ${{ values.database | default(values.domain, true) | replace(r/domain:| |-/, "") | upper | dump}}
      schema: ${{ (values.schema | default(values.dataproduct.split(".")[1], true) | replace(r/ |-/g, "") + "_" + values.identifier.split(".")[2]) | upper | dump }}
      tables:
      - tableName: ${{ values.tableName }}
        schema: {% if values.schemaColumns | length > 0 %}{% for i in values.schemaColumns %}
          - name: ${{ i.name }}
            dataType: ${{ i.dataType }}{% if i.constraint is defined and i.constraint != '(no constraint)' %}
            constraint: ${{ i.constraint }}{% endif %}{% if i.dataLength is defined and i.dataType == 'TEXT' %}
            dataLength: ${{ i.dataLength }}{% endif %}{% if i.precision is defined and i.dataType == 'NUMBER' %}
            precision: ${{ i.precision }}{% endif %}{% if i.scale is defined and i.dataType == 'NUMBER' %}
            scale: ${{ i.scale }}{% endif %}
            tags: {% if i.businessTerms | length > 0 or i.piiCheck %}
              {% if i.businessTerms | length > 0 %}
                {% for j in i.businessTerms %}
              - tagFQN: ${{ j }}
                source: Glossary
                labelType: Manual
                state: Confirmed
                {% endfor %}
              {% endif %}
              {% if i.piiCheck %}
              - tagFQN: PII
                source: Tag
                labelType: Manual
                state: Confirmed
              {% endif %}
            {% else %}[]{% endif %}{% endfor %}{% else %}[]{% endif %}